### ISSUE TITLE
Allow option to pass in precision for LLtoUTM coordinates

### ISSUE THREAD

**Issue by robonyong** [csbrandt/WGS84Util#3]
Hallo, it'd be nice to be able to passing in a `precision`-like variable for the coordinates returned from `LLtoUTM`. Right now they're hard-coded at 1 (https://github.com/csbrandt/WGS84Util/blob/master/index.js#L279), and the project I'm working on may require a little more precision. Even pinning this to 10 to match `UTMtoLL` would be great.

**Comment by csbrandt** [comment]
@robonyong the UTM coordinates are fixed to decimeter precision which is representative of the expected accuracy of the calculations.

> the project I'm working on may require a little more precision

Interesting, is your use case scientific in nature? If you require accuracy better than ±1 meter consider [using a different datum to account for tectonic shift](http://www.movable-type.co.uk/scripts/latlong-vincenty.html#datums).

> Even pinning this to 10 to match UTMtoLL would be great.

`10` places for decimal latitude/longitude precision which is precise within 11.11 micrometers. This precision could be fixed lower since the accuracy of the datum used in the calculations (WGS-84) is no better than ±1 meter.

**Comment by robonyong** [comment]
Thanks for taking the time to answer! The work is pretty scientific, but after talking to the folks receiving the data, it looks like for now they're happy to stick with 1 precision & will let me know if there's any issue. I'll close this issue :)
